Issue 40 upload venue banner new
Appitzr-Project/Backend-Venue-Profile pull request #15
Opened 2021-05-10 08:41 UTC by irmanherdiana

Fixed pull request to staging

2021-05-10 09:38 UTC, JuniYadi requested changes
1. Error ketika upload: ValidationException: One of the required keys was not given a value
2. body value nya harus nya bukan profilePicture, tapi banner

Screenshoot terlampir

![Screenshot_424](https://user-images.githubusercontent.com/31454084/117639443-1df5b580-b1ae-11eb-8fe4-30158d202f65.png)

2021-05-10 19:46 UTC, irmanherdiana commented
changes request is done, please check.
![image](https://user-images.githubusercontent.com/66599140/117715841-04cb2400-b203-11eb-8276-48c853fe6224.png)

2021-05-10 22:37 UTC, JuniYadi requested changes
Update 1 lagi ya sesuai comment

2021-05-10 22:37 UTC, JuniYadi commented on controller/profileVenueController.ts
> +import { Console } from "console";
ini di hapus aja kalau ga di pakai

2021-05-11 01:12 UTC, irmanherdiana commented on controller/profileVenueController.ts
> +import { Console } from "console";
> ini di hapus aja kalau ga di pakai

Kok ada itu ya? persaaan gak nambahin itu. apa otomatis ya karena sempat coba2 pakai console.log.

2021-05-11 06:29 UTC, JuniYadi commented on controller/profileVenueController.ts
> +import { Console } from "console";
bisa jadi

2021-05-11 06:30 UTC, JuniYadi approved these changes
LGTM

2021-05-11 06:30 UTC, merged